# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY . .

# Specify the port the app will run on
EXPOSE 5001

# Run app.py when the container launches
CMD ["gunicorn", "--bind", "0.0.0.0:5001", "app:app"]
